### ISSUE TITLE
H2 DB File not being set on filesystem

### ISSUE THREAD

**Issue by plungu** [camunda/camunda-archetypes#12]
It appears the the spring.datasource.url is not being picked up any more with 7.9. I tried passing it on the command line. Also adding a .properties file. 
The effect is springboot seems to be only using the in mem h2 db. 
The expected behavior would be when the datasource is set as follows it would use the filesysystem DB not the in mem DB.
spring.datasource.url=jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE

**Comment by falko** [comment]
Did you find a fix for this in the end?

**Comment by plungu** [comment]
The fix is to add the spring-boot-jdbc dependency. Last time I tried 7.9 it was part of 7.9 archetype.

Cheers

Paul Lungu
Technical Consultant
P: 720 634 5971
Schedule time with me
https://calendly.com/paul-lungu

On Jul 23, 2018, at 9:47 AM, Falko Menge <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you find a fix for this in the end?

**Comment by tmetzke** [comment]
Solved with https://github.com/camunda/camunda-archetypes/commit/6cdd3da73500276e00016358d88bd1f54352afc5
