### ISSUE TITLE
archetypes url appears to be done

### ISSUE THREAD

**Issue by gsvitak** [camunda/camunda-archetypes#8]
Hello,

I am trying to build a plugin and it appears the archetypes repository is down. I clicked on the following link and I am receiving a 503 Service Temporarily Unavailable

https://app.camunda.com/nexus/content/repositories/camunda-bpm/

Any suggestions?
Thanks
G

**Comment by hawky-4s-** [comment]
Hi, we had a short outage of the nexus service tonight. It is back up again
and running. If you still experience problems, please report them.
Am 17.02.2016 02:37 schrieb "gsvitak" <notifications@github.com>:

**Comment by swapniljha001** [comment]
I believe that this issue has been resolved as per the last conversation, kindly close the issue to avoid confusion.
